#!/bin/bash

set -a
source ".env"
set +a

## For testing only
CI_JOB_JWT=eyJraWQiOiJ6eDJVUWtOeDJnUVA2NVd0WUlpLWEyNHo2WlQxV25KU0RoYjAxM19lRE9zIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJuYW1lc3BhY2VfaWQiOiIyIiwibmFtZXNwYWNlX3BhdGgiOiJkZW1vcyIsInByb2plY3RfaWQiOiIxIiwicHJvamVjdF9wYXRoIjoiZGVtb3MvY29uanVyLWNsb3VkLWRlbW8iLCJ1c2VyX2lkIjoiMSIsInVzZXJfbG9naW4iOiJyb290IiwidXNlcl9lbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicGlwZWxpbmVfaWQiOiI4IiwicGlwZWxpbmVfc291cmNlIjoicHVzaCIsImpvYl9pZCI6IjE1IiwicmVmIjoibWFpbiIsInJlZl90eXBlIjoiYnJhbmNoIiwicmVmX3BhdGgiOiJyZWZzL2hlYWRzL21haW4iLCJyZWZfcHJvdGVjdGVkIjoidHJ1ZSIsInJ1bm5lcl9pZCI6NywicnVubmVyX2Vudmlyb25tZW50Ijoic2VsZi1ob3N0ZWQiLCJzaGEiOiI3ODVkYTAyZDEzMDQ0M2E4NjZmZTY3YThhNDk3NTdkMzY2OWI4YWIzIiwicHJvamVjdF92aXNpYmlsaXR5IjoicHJpdmF0ZSIsImNpX2NvbmZpZ19yZWZfdXJpIjoiZ2l0bGFiLmRlbW8uY3lici9kZW1vcy9jb25qdXItY2xvdWQtZGVtby8vLmdpdGxhYi1jaS55bWxAcmVmcy9oZWFkcy9tYWluIiwiY2lfY29uZmlnX3NoYSI6Ijc4NWRhMDJkMTMwNDQzYTg2NmZlNjdhOGE0OTc1N2QzNjY5YjhhYjMiLCJqdGkiOiIyYTJlZGIzMy1kMjQ2LTRlOGYtYTI0ZC1mZWJjMWM5N2RkMTEiLCJpc3MiOiJodHRwczovL2dpdGxhYi5kZW1vLmN5YnIiLCJpYXQiOjE2OTk2MDg0MjUsIm5iZiI6MTY5OTYwODQyMCwiZXhwIjoxNjk5NjEyMDI1LCJzdWIiOiJwcm9qZWN0X3BhdGg6ZGVtb3MvY29uanVyLWNsb3VkLWRlbW86cmVmX3R5cGU6YnJhbmNoOnJlZjptYWluIiwiYXVkIjoiaHR0cHM6Ly9naXRsYWIuZGVtby5jeWJyIn0.P9ss-j5StoIEdQgg_87Oe7OTNMd_gzm6gRyUspUNVwWyXYGPrC7Uo6hyiCr9_sSSZ7pDggcyCGtXe97jQEWXGXR465KCX7trf_LKeBDqJfazyL1dJEGdX28WGzj4td1XlgsriSqJZWA_Do2aUF2i9EIYLQ_HeHRuANQtumvMyZr-39-RKHmYkGmhl5KThpESICfW6qjlNTQcexMROp0sA0n1TkfwmRKb9empIQ0GYJdlVbMSh5GP_p7V6yvJeZxLbvuUGTnFoEjz3Iz_OhHfUZxL2sJHDjy771Ja4wUIgsugUmwAJ8-fbfxIbhXnxRbxA7DRQR1sZTSnpA9CxMa02g

CONJUR_URL=https://emeadevops.secretsmgr.cyberark.cloud/api/authn-jwt/$CONJUR_AUTHENTICATOR_ID/conjur/authenticate

response="$(curl -k -s -w '%{http_code}' --request POST "$CONJUR_URL" --header 'Content-Type: application/x-www-form-urlencoded' --header "Accept-Encoding: base64" --data-urlencode "jwt=$CI_JOB_JWT")"
http_code=${response: -3}

if [[ $http_code -ne 200 ]]; then
  echo "Gitlab Authentication failed $response"
  exit 1
else
  echo "Gitlab Authentication successful!"
fi
